<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Loyalty_details.aspx.cs" MasterPageFile="~/Site.Master" Inherits="DatabaseCW.Loyalty_details" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
        <div class ="RestaurantHeadings">
        <h1>Insertion of Loyalty Details</h1>
        </div>
        <div class ="Dish_field">
         <asp:Label class="Labels" ID="Lid" runat="server" Text="Loyalty id:"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox class="TextField" ID="LidTXT" runat="server"></asp:TextBox><br /><br />
        <asp:Label class="Labels" ID="Lscore" runat="server" Text="Loyalty score:"></asp:Label>
        &nbsp;<asp:TextBox class="TextField" ID="LscoreTXT" runat="server"></asp:TextBox><br /><br />
        <asp:Label class="Labels" ID="Ldescription" runat="server" Text="Description:"></asp:Label>
        &nbsp;&nbsp;&nbsp;
        <asp:TextBox class="TextField" ID="LdescriptionTXT" runat="server" TextMode="MultiLine"></asp:TextBox><br /><br />
        <asp:Label class="Labels" ID="DishCode" runat="server" Text="Dish code:"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:DropDownList class="TextField" ID="DishcodeDropDown" runat="server" DataSourceID="DishCodeDropData" DataTextField="DISH_CODE" DataValueField="DISH_CODE"></asp:DropDownList><br />
        <asp:SqlDataSource ID="DishCodeDropData" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString5 %>" ProviderName="<%$ ConnectionStrings:ConnectionString5.ProviderName %>" SelectCommand="select * from Dish"></asp:SqlDataSource>
         <br />
        <asp:Label class="Labels" ID="RestaurantId" runat="server" Text="Restaurant Id:"></asp:Label>
        <asp:DropDownList class="TextField" ID="RestaurantIdDropDown" runat="server" DataSourceID="RestaurantDrop" DataTextField="RESTAURANT_ID" DataValueField="RESTAURANT_ID"></asp:DropDownList>
        <asp:SqlDataSource ID="RestaurantDrop" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString5 %>" ProviderName="<%$ ConnectionStrings:ConnectionString5.ProviderName %>" SelectCommand="select * from Restaurant"></asp:SqlDataSource>
        <asp:Button class="InsertBTN" ID="Insertbtn" runat="server" Text="Insert" OnClick="Insertbtn_Click" />
        </div>
        <asp:GridView class= "GridData" ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="LOYALTY_ID" DataSourceID="Loyaltydata" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="0" BorderStyle="None">
            <EditRowStyle Height="0px" Width="0px" Wrap="True" />
            <HeaderStyle BackColor="#5D7B9D" ForeColor="White" font-size="12px" Height="27px" />   
            <Columns>
                <asp:BoundField DataField="LOYALTY_ID" HeaderText="LOYALTY_ID" ReadOnly="True" SortExpression="LOYALTY_ID" />
                <asp:BoundField DataField="LOYALTY_SCORE" HeaderText="LOYALTY_SCORE" SortExpression="LOYALTY_SCORE" />
                <asp:BoundField DataField="DESCRIPTION" HeaderText="DESCRIPTION" SortExpression="DESCRIPTION" />
                <asp:BoundField DataField="DISH_CODE" HeaderText="DISH_CODE" SortExpression="DISH_CODE" />
                <asp:BoundField DataField="RESTAURANT_ID" HeaderText="RESTAURANT_ID" SortExpression="RESTAURANT_ID" />
            </Columns>
            <RowStyle ForeColor="#BCC6CC" Height="27px" HorizontalAlign="Center" VerticalAlign="Middle" />
            </asp:GridView>

            <asp:SqlDataSource ID="Loyaltydata" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString5 %>" ProviderName="<%$ ConnectionStrings:ConnectionString5.ProviderName %>" SelectCommand="Select * from Loyalty_point" DeleteCommand="DELETE FROM LOYALTY_POINT WHERE (LOYALTY_ID = :LOYALTY_ID)" UpdateCommand="UPDATE LOYALTY_POINT SET LOYALTY_SCORE = :loyalty_score, DESCRIPTION = :description, DISH_CODE = :dish_code, RESTAURANT_ID = :restaurant_id WHERE (LOYALTY_ID = :LOYALTY_ID)">
                <DeleteParameters>
                    <asp:Parameter Name="LOYALTY_ID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="loyalty_score" />
                    <asp:Parameter Name="description" />
                    <asp:Parameter Name="dish_code" />
                    <asp:Parameter Name="restaurant_id" />
                    <asp:Parameter Name="LOYALTY_ID" />
                </UpdateParameters>
            </asp:SqlDataSource>
</asp:Content>
